version: '3.8'

services:
  ai-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
